grano: 3.6
mais: 7.2
soia: 10.8
carote: 7.2
mangime_galline: 7.2
mangime_mucca: 14.4 
mangime_maiale: 14.4
mangime_pecora: 14.4
uova: 18
latte: 32.4
pancetta: 50.4
lana: 54
pane_integrale: 72
pane: 21
panna: 50
burro: 82
formaggio: 122
pancetta_uova: 201
hamburger: 169
maglione: 151
pasticcio_carote: 82
pasticcio_pancetta: 219
pasticcio_pancetta: 219
  